#ifndef SET_CHAR_BS
#define SET_CHAR_BS

#include <lcd/lcd_def.bs>

set_char(char, data)
{
    let line;
``
    lda .char
    lsh
    lsh
    lsh
    ora #LCD_CGRAM
    sta .char
    lda #7
.loop:
    sta .line
    ora .char
    lcc
    lda .data
    add .line
    tax
    lda .data + 1
    adc #0
    tay
    lda x, y
    lcd
    lda .line
    dec
    jpc .loop
    lda #LCD_DDRAM
    lcc
``
}

#endif

