#ifndef PUTD_BS
#define PUTD_BS

#include <math/div_base.bs>

putd(n)
{
``
    lda .n
    sta div_base_.x
    lda .n + 1
    sta div_base_.x + 1
    lda #10
    sta div_base_.y
    ldy #0
    sty div_base_.y + 1
.get_digit:
    phy
    call div_base_
    ply
    lda div_base_.remainder
    pha
    iny
    lda div_base_.x
    sub #0
    jnz .get_digit
    lda div_base_.x + 1
    sub #0
    jnz .get_digit
.print:
    pla
    add #'0'
    lcd
    dey
    jnz .print
``
}

#endif

